server:
  port: 7777

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/bokydb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: eddi@123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

#  logging:
#    level:
#      org.hibernate:
#        type.descriptor.sql: trace #show parameter binding
#        SQL: DEBUG

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB


